name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        working-directory: ./backend
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff mypy pytest httpx

      - name: Lint
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          ruff check .
          black --check .
          mypy .
